# Config file for automatic testing at travis-ci.org
dist: xenial

language: python

python:
    - 3.7
    - 3.8
    - 3.9

os:
    - linux

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/codacy

notifications:
    email: false

install:
    - pip install pytest-cov
    - pip install --quiet .[dev]

script:
    - flake8
    - black --check .
    - python setup.py check --restructuredtext
    - pytest --cov-report=xml --cov=popv --internet-tests

after_success:
    - codecov
    - pip list
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Python -r coverage.xml

branches:
    only:
        - master
        - dev
